name: Bug Report
description: Report something that isn't working correctly
labels: ["type:bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug. Please be specific so it can be reproduced.

  - type: textarea
    id: problem
    attributes:
      label: Problem
      description: What is broken?
      placeholder: Describe what's happening vs what should happen.
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: Steps to Reproduce
      description: How can we reproduce this?
      placeholder: |
        1. Go to...
        2. Run...
        3. See error...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What should happen instead?
    validations:
      required: true

  - type: textarea
    id: notes
    attributes:
      label: Notes
      description: Any additional context, logs, or screenshots
    validations:
      required: false

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      options:
        - p2 (normal)
        - p1 (high)
        - p0 (critical)
    validations:
      required: true

  - type: dropdown
    id: area
    attributes:
      label: Area
      options:
        - modules
        - exercises
        - docs
        - video
    validations:
      required: true
