name: Exercise Help
description: Stuck on a specific exercise? Ask for help here.
title: "[Help]: <Exercise Name>"
labels: ["help wanted", "exercise"]
body:
  - type: dropdown
    id: module
    attributes:
      label: Which Module?
      description: Select the module you are working on.
      options:
        - 01 - Getting Started
        - 02 - Skills & Workflows
        - 03 - Speed & Efficiency
        - 04 - Planning & Execution
        - 05 - Quality & Verification
        - 06 - Domain Patterns
        - 07 - Advanced Integration
        - 08 - API Internals
        - 09 - API Customization
    validations:
      required: true
  - type: textarea
    id: problem
    attributes:
      label: What happened?
      description: Describe what you were trying to do and what went wrong.
      placeholder: I tried to run the command but got this error...
    validations:
      required: true
  - type: textarea
    id: prompt
    attributes:
      label: Your Prompt
      description: Paste the exact prompt you sent to Codex.
      render: markdown
    validations:
      required: false
  - type: textarea
    id: output
    attributes:
      label: Codex Output
      description: Paste the relevant part of Codex's response or error message.
      render: markdown
